version: '3.4'

services:
  polyclinic:
    image: ${DOCKER_REGISTRY-}polyclinic
    build:
      context: .
      dockerfile: Polyclinic\Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001" 

  polyclinic.database:
    image: postgres:latest
    container_name: polyclinic.database
    environment:
        - POSTGRES_DB=polyclinicdb
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=123
    volumes:
      - ./.containers/polyclinic-db:/var/lib/postgresql/data
    ports:
      - 5432:5432
